" mhs's vimrc
" It's a Unix system, I know this.

set nocompatible
set encoding=utf-8
syntax on
set number
set shell=/bin/bash
set ruler
set rulerformat=%=%P
set backspace=indent,eol,start
set autoread
set hidden
set history=1000
set ttimeout
set ttimeoutlen=100
set showcmd
set autoindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set scrolloff=5
set nowrap
set title
set ignorecase
set smartcase
set hlsearch
" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
	nnoremap <silent> <C-L> :nohlsearch<CR><C-L>
endif
set incsearch
set noerrorbells
set backupdir=~/.vim/backup//   " move backup/swap/undo files to central location
set directory=~/.vim/swap//     " double slashes force vim to avoid name collisions
set undodir=~/.vim/undo//

noremap , :

" Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'elixir-lang/vim-elixir'
Plugin 'slashmili/alchemist.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'dleonard0/pony-vim-syntax'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'chriskempson/base16-vim'
Plugin 'jpo/vim-railscasts-theme'
call vundle#end()
filetype plugin indent on

let g:syntastic_php_checkers = ['php']
let g:syntastic_javascript_checkers = ['eslint']

set background=dark

if has("gui_macvim")
	colorscheme base16-monokai
	autocmd BufNew,BufEnter *.php,*.js colorscheme base16-monokai
	autocmd BufNew,BufEnter *.ex,*.exs,*.eex colorscheme railscasts
else
	colorscheme railscasts
endif

autocmd BufWritePre * :%s/\s\+$//e   "strip all trailing whitespace
