" Hew's vimrc
" It's a Unix system, I know this.

set nocompatible
set encoding=utf-8
syntax on
set number
set backspace=indent,eol,start
set autoread
set hidden
set autoindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set nowrap
set title
set ignorecase
set smartcase
set hlsearch
set noerrorbells
set backupdir=~/.vim/backup//  " move backup/swap/undo files to central location
set directory=~/.vim/swap//    " double slashes force vim to avoid name collisions
set undodir=~/.vim/undo//

filetype off

" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'elixir-lang/vim-elixir'
Plugin 'pangloss/vim-javascript'
call vundle#end()

filetype plugin indent on
