alias phpgrep='find . -type f -name "*.php" -print0 | xargs -0 grep -n $1'
alias jsgrep='find . -type f -name "*.js" -print0 | xargs -0 grep -n $1'
alias exgrep='find . -type f -name "*.ex" -print0 | xargs -0 grep -n $1'

alias c='cd ~/code'
alias d='cd ~/Downloads'
alias dt='cd ~/Desktop'

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
